version: '3.1'

services:
    link-docker-postgresql:
        image: "postgres:11-alpine"
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=JOLLY
            - POSTGRES_PASSWORD=200900
            - POSTGRES_DB=GRE3000
        volumes:
            - /root/pg_data:/var/lib/postgresql/data

    gre_service_31011:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "31011:8080"
        volumes:
            - /root/logs/gre-service:/go/src/GRE3000/logs
            - /root/static/upload/avatar:/go/src/GRE3000/static/upload/avatar

    gre_service_31012:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "31012:8080"
        volumes:
            - /root/logs/gre-service:/go/src/GRE3000/logs
            - /root/static/upload/avatar:/go/src/GRE3000/static/upload/avatar
