version: '2'

services:

  link-docker-redis:
    image: "redis:alpine"

  gre_service_31011:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/GRE3000
#      - /home/dlnu/logs/gre-service:/go/src/GRE3000/logs
#      - /home/dlnu/GRE3000/static/upload/avatar:/go/src/GRE3000/static/upload/avatar
    ports:
      - "31011:8080"
#
#  gre_service_31012:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      volumes:
#        - /home/dlnu/logs/gre-service:/go/src/GRE3000/logs
#        - /home/dlnu/GRE3000/static/upload/avatar:/go/src/GRE3000/static/upload/avatar
#      ports:
#        - "31012:8080"
#
#  gre_service_31013:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      volumes:
#        - /home/dlnu/logs/gre-service:/go/src/GRE3000/logs
#        - /home/dlnu/GRE3000/static/upload/avatar:/go/src/GRE3000/static/upload/avatar
#      ports:
#        - "31013:8080"
#
#  gre_service_31014:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      volumes:
#        - /home/dlnu/logs/gre-service:/go/src/GRE3000/logs
#        - /home/dlnu/GRE3000/static/upload/avatar:/go/src/GRE3000/static/upload/avatar
#      ports:
#        - "31014:8080"
