version: '2'

services:

  # REDIS
  link-docker-redis:
    image: "redis:alpine"


  # wx_service_cluster
  # wx_service_cluster
  # wx_service_cluster

  gre_service_31011:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /root/logs/gre-service:/go/src/GRE3000/logs
    ports:
      - "31011:8080"
