services:
    link-docker-postgresql:
        image: postgres:17-alpine
        restart: always
        ports:
            - "53501:5432"
        environment:
            POSTGRES_USER: DAISY
            POSTGRES_PASSWORD: 778899
            POSTGRES_DB: GRE3000
        volumes:
            - /opt/GRE3000/pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U JOLLY -d GRE3000"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - backend

    gre_service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            link-docker-postgresql:
                condition: service_healthy
        ports:
            - "53502:3000"
        volumes:
            - /opt/GRE3000/logs/gre-service:/go/src/GRE3000/logs
            - /opt/GRE3000/static/upload/avatar:/go/src/GRE3000/static/upload/avatar
        networks:
            - backend

networks:
    backend:
        driver: bridge